title: Michael Humphriss
logo: docs/assets/headshot_circle.jpg
description: Games Engineer | Software Engineer
links: https://www.linkedin.com/in/michael-humphriss-66a751250/
theme: jekyll-theme-minimal
