title: Michael Humphriss
logo: docs/assets/headshot_circle.jpg
description: 
- Games Engineer | Software Engineer LinkedIn                 

- <a href="https://www.linkedin.com/in/michael-humphriss-66a751250/">: Here</a>
theme: jekyll-theme-minimal
